# Generated by Django 4.2.7 on 2025-08-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, help_text='Student record this user account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='authentication.student'),
        ),
    ]
