# Generated by Django 4.2.7 on 2025-09-04 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(help_text='Original filename from user', max_length=255)),
                ('file_name', models.CharField(help_text='Stored filename (UUID-based)', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], max_length=20)),
                ('mime_type', models.CharField(help_text='MIME type (e.g., image/jpeg)', max_length=100)),
                ('file_url', models.URLField(help_text='S3 URL to access file')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail URL for images', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_complete', models.BooleanField(default=False, help_text='Upload finished successfully')),
                ('processing_complete', models.BooleanField(default=True, help_text='File processing done')),
                ('conversation', models.ForeignKey(help_text='Which conversation this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.conversation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['conversation', 'uploaded_at'], name='chat_files_convers_a52395_idx'), models.Index(fields=['uploaded_by', 'uploaded_at'], name='chat_files_uploade_ea6068_idx'), models.Index(fields=['file_type'], name='chat_files_file_ty_03667c_idx')],
            },
        ),
    ]
